---
version: '2.4'

services:

  manage-case-assignment:
    image: "${MANAGE_CASE_USE_LOCAL-hmctspublic.azurecr.io/}aac/manage-case-assignment:${MANAGE_CASE_TAG:-pr-27-4d66f4f2}"
    environment:
      SERVER_PORT: 4454
      IDAM_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}" # https://idam-web-public.aat.platform.hmcts.net
      S2S_URL: http://service-auth-provider-api:8080 # http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      MANAGE_CASE_S2S_KEY: "${S2S_KEY_MANAGE_CASE_ASSIGNMENT}" # use aat key from vault
      MANAGE_CASE_S2S_AUTHORISED_SERVICES: ccd_gw,xui_webapp
      CCD_DATA_STORE_HOST: http://ccd-data-store-api:4452 # http://ccd-data-store-api-aat.service.core-compute-aat.internal
      PRD_HOST: http://rd-professional-api:8090 # http://rd-professional-api-aat.service.core-compute-aat.internal
    ports:
      - 4454:4454
    depends_on:
      # Uncomment this line to enable ccd test stub service
      #     ccd-test-stubs-service:
      #       condition: service_started
      idam-api:
        condition: service_started
      ccd-shared-database:
        condition: service_started
    networks:
      - ccd-network

  rd-professional-api:
    image: "${PRD_API_USE_LOCAL-hmctspublic.azurecr.io/}rd/professional-api:${PRD_API_TAG:-latest}"
    environment:
      SERVER_PORT: 8090
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_NAME: dbrefdata
      POSTGRES_HOST: ccd-shared-database
      POSTGRES_PORT: 5432
      S2S_URL: http://service-auth-provider-api:8080
      S2S_SECRET: "${S2S_KEY_RD_PROFESSIONAL_API}"
      PRD_S2S_AUTHORISED_SERVICES: aac_manage_case_assignment
      USER_PROFILE_URL: http://rd-user-profile-api:8091
      CCD_URL: http://ccd-user-profile-api:4453
      OPEN_ID_API_BASE_URI: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/o"
      IDAM_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      #prdEnumRoleType: ADMIN_ROLE,JURISD_ID,CCD_ROLE
    ports:
      - 8090:8090
    depends_on:
      # Uncomment this line to enable ccd test stub service
      #     ccd-test-stubs-service:
      #       condition: service_started
      idam-api:
        condition: service_started
      ccd-shared-database:
        condition: service_started
    networks:
      - ccd-network
  rd-user-profile-api:
    image: "${PRD_API_USE_LOCAL-hmctspublic.azurecr.io/}rd/user-profile-api:${PRD_API_TAG:-latest}"
    environment:
      SERVER_PORT: 8091
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_NAME: dbuserprofile
      POSTGRES_HOST: ccd-shared-database
      POSTGRES_PORT: 5432
      S2S_URL: http://service-auth-provider-api:8080
      OPEN_ID_API_BASE_URI: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/o"
      IDAM_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
    ports:
      - 8091:8091
    depends_on:
      # Uncomment this line to enable ccd test stub service
      #     ccd-test-stubs-service:
      #       condition: service_started
      idam-api:
        condition: service_started
      ccd-shared-database:
        condition: service_started
    networks:
      - ccd-network
networks:
  ccd-network:
    external: true
