---
version: '2.4'
#add non core CCD services here

networks:
  ccd-network:
    external: true

services:
  mv-annotation-api:
    image: hmctspublic.azurecr.io/em/anno:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://annotation-api-db:5432/emannotationapp
      - SPRING_DATASOURCE_USERNAME=emannotationapp
      - SPRING_DATASOURCE_PASSWORD=emannotationapp
      - S2S_BASE_URI=http://service-auth-provider-api:8080
      - ENABLE_LIQUIBASE=true
      - S2S_NAMES_WHITELIST=sscs,divorce,ccd,em_gw,jui_webapp,pui_webapp,em_npa_app,ccd_gw,ccd_gateway
      - IDAM_API_BASE_URI=http://sidam-api:5000
    depends_on:
      - mv-annotation-api-db
    ports:
      - 4623:8080

  mv-annotation-api-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=emannotationapp
      - POSTGRES_USER=emannotationapp
      - POSTGRES_PASSWORD=emannotationapp
    ports:
      - 5444:5432
    volumes:
      - ccd-docker-mv-annotation-api-db-data:/var/lib/postgresql/data

volumes:
  ccd-docker-mv-annotation-api-db-data: