# just a copy of
---
version: '2.4'

services:
  fr-am:
    image: hmctsprivate.azurecr.io/idam/idam-fr-am:latest
    hostname: localam
    depends_on:
      shared-db:
        condition: service_started
  fr-idm:
    image: hmctsprivate.azurecr.io/idam/idam-fr-idm:latest
    hostname: localidm
    depends_on:
      fr-am:
        condition: service_started
      shared-db:
        condition: service_started
  shared-db:
    image: hmctsprivate.azurecr.io/idam/shared-db:latest
  smtp-server:
    image: mailhog/mailhog
  idam-api:
    image: hmctspublic.azurecr.io/idam/api:preview
    depends_on:
      fr-am:
        condition: service_started
      shared-db:
        condition: service_started
  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:preview
    depends_on:
      idam-api:
        condition: service_started
  idam-web-admin:
    image: hmctspublic.azurecr.io/idam/web-admin:preview
    depends_on:
      idam-api:
        condition: service_started
